fix bug when frontend crashes when loading available processors
Super annoying to find, but apparently since updating webtool\templates\components\processor-option.html from `{{ option_settings.help }}` to `{{ option_settings.help|markdown|safe }}`, the frontend would crash with 500 and "jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'help'" since `help` is only populated in the column_filter processor when a parent_dataset is passed to `get_options`.