Squashed commit of the following:
commit 513a58986cc518bb42c59eb4fb947e2f83eb3c43
Author: Dale Wahl <dalewahl@gmail.com>
Date:   Mon Jan 27 17:01:52 2025 +0100

    bsky: ensure interrupt

commit 0badee73d919aece92134fc942540c83294861f0
Author: Dale Wahl <dalewahl@gmail.com>
Date:   Mon Jan 27 15:19:42 2025 +0100

    bsky: no progress bar if no max_posts

commit 115a3c155f1c5edbce3d6c62c1fbbf66fa6a51ba
Author: Dale Wahl <dalewahl@gmail.com>
Date:   Mon Jan 27 14:18:12 2025 +0100

    bsky datasource

commit 836a23531e3cbbbc5cd5d8e2a195b83bba0211ae
Author: Dale Wahl <dalewahl@gmail.com>
Date:   Thu Jan 23 11:47:51 2025 +0100

    post_topic_matrix: rename column when tokenizer created multiple documents per post

commit 977d887ccf99d38c4971876755538d54af92e577
Author: Dale Wahl <dalewahl@gmail.com>
Date:   Thu Jan 23 11:37:52 2025 +0100

    rank_attribute: convert to str to lower()

commit a1cdd4ce49c70f38e99ff71b747c55e3819ad56b
Author: Dale Wahl <dalewahl@gmail.com>
Date:   Wed Jan 22 09:40:29 2025 +0100

    fix: allow None for columns.default; remove debug log statement

    fix occasional error that appears particularly on new processors with no expected default, i.e.:
    <option value="{{ choice }}"{% if choice in option_settings.default %} selected="selected"{% endif %}>{{ option_settings.options[choice] }}</option>
    TypeError: argument of type 'NoneType' is not iterable