fix: do not fail when no processor exists
weird! failed on a dataset `type="custom-search"` which was created by an import script w/ no processor. Also likely would make deprecated processors fail.
500 server error:
```
File "/opt/4cat/common/lib/dataset.py", line 800, in get_columns
     return self.get_item_keys(processor=self.get_own_processor())
   File "/opt/4cat/common/lib/dataset.py", line 405, in get_item_keys
     keys = list(items.__next__().keys())
   File "/opt/4cat/common/lib/dataset.py", line 337, in iterate_items
     if own_processor.map_item_method_available(dataset=self):
 AttributeError: 'NoneType' object has no attribute 'map_item_method_available'
```