setup.py change: typing_extensions currently has a conflict with spacy
resolves this:
Traceback (most recent call last):
  File "4cat-daemon.py", line 249, in <module>
    start()
  File "4cat-daemon.py", line 131, in start
    import backend.bootstrap as bootstrap
  File "/usr/src/app/common/lib/../../backend/__init__.py", line 7, in <module>
    all_modules = ModuleCollector()
  File "/usr/src/app/common/lib/module_loader.py", line 49, in __init__
    self.load_modules()
  File "/usr/src/app/common/lib/module_loader.py", line 99, in load_modules
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/src/app/common/lib/../../processors/text-analysis/get_nouns.py", line 9, in <module>
    import spacy
  File "/opt/venv/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/opt/venv/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/opt/venv/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/opt/venv/lib/python3.8/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/opt/venv/lib/python3.8/site-packages/spacy/schemas.py", line 222, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class